### ISSUE TITLE
Process line by line

### ISSUE THREAD

**Issue by a1300** [ffuf/pencode#34]
Thanks for this wonderful library!

I want to pipe a whole text file line-by-line through `pencode` and then to `ffuf`.
It seems that `pencode` is encoding/decoding the whole file and not line-by-line.

```bash
cat special.txt
&
=
```

When I pipe this to `pencode` the newline vanishes.

```bash
cat special.txt | pencode urlencode
%26%3D
```

Am I missing something?
If this is the intended way would it be possible to add a switch that makes `pencode`  process stdin line-by-line?

@joohoi

**Comment by joohoi** [comment]
This was fixed in #33

**Comment by a1300** [comment]
Thanks :+1: 
Will there be a new release in the near future?

**Comment by joohoi** [comment]
Yeah, there will. If not during this weekend, it will be done next week.
